# required env variables:
#
# ESGF_CONFIG : points to the root ESGF configuration directory
#       example: export ESGF_CONFIG=/Users/cinquini/ESGF_CONFIG
# SOLR_DATA_DIR : points to Solr index directory
# 	example: export SOLR_DATA_DIR=/esg/solr-index
# TDS_CONTENT_ROOT : point to root directory above TDS catalogs thredds/
#       example: export TDS_CONTENT_ROOT=/esg/content
# DOCKER_IP: HostName or IP address for apache httpd front-end server
#       example: export DOCKER_IP=my.esgf.node
#       example: export DOCKER_IP=`docker-machine ip`

version: '2'

networks:
  mynet:
    external:
      name: mynetwork

services:

  esgf_data_node_app:
    expose:
      - "8080"
      - "8443"
    ports:
      - "8080:8080"
      - "8443:8443"
    image: esgfhub/esgf-data-node
    container_name: esgf-data-node
    networks:
      default: {}
      mynet: {}
    volumes:
      - $ESGF_CONFIG/esg/config/:/esg/config/
      - $TDS_CONTENT_ROOT:/esg/content
    depends_on:
      - esgf_postgres_app

  esgf_idp_app:
    expose:
      - "8080"
      - "8443"
    ports:
      - "8082:8080"
      - "8445:8443"
    image: esgfhub/esgf-idp
    container_name: esgf-idp
    networks:
      default: {}
      mynet: {}
    volumes:
      - $ESGF_CONFIG/esg/config/:/esg/config/
    depends_on:
      - esgf_postgres_app
    environment:
     - ESGF_HOME=/esg

  esgf_solr_app:
    expose:
      - "8983"
      - "8984"
    ports:
      - "8983:8983"
      - "8984:8984" 
    image: esgfhub/esgf-solr
    container_name: esgf_solr
    volumes:
     - $SOLR_DATA_DIR:/esg/solr-index

  esgf_search_app:
    image: esgfhub/esgf-search
    expose:
      - "8080"
      - "8443"
    ports:
      - "8081:8080"
      - "8444:8443"
    depends_on:
      - esgf_solr_app
    volumes:
      - $ESGF_CONFIG/esg/config/:/esg/config/
    container_name: esgf_search

  esgf_postgres_app:
     image: esgfhub/esgf-postgres
     expose:
       - "5432"
     ports:
       - "5432:5432"
     container_name: esgf_postgres

  esgf_cog_app:
     image: esgfhub/esgf-cog
     expose:
       - "8000"
     ports:
       - "8000:8000"
     volumes:
       - $PWD/cog/esgf-cog_settings.cfg:/usr/local/cog/cog_config/esgf-cog_settings.cfg
       - $ESGF_CONFIG/cog/cog_config/:/usr/local/cog/cog_config/
       - $ESGF_CONFIG/esg/config/:/esg/config/
     command: $DOCKER_IP true false
     container_name: esgf_cog
     depends_on:
       - esgf_postgres_app
     #  - esgf_search_app

  esgf_httpd_app:
   volumes:
     - $ESGF_CONFIG/httpd/certs/:/etc/certs/
     - $ESGF_CONFIG/httpd/conf/esgf-httpd.conf:/etc/httpd/conf.d/esgf-httpd.conf
     - $ESGF_CONFIG/grid-security/certificates/:/etc/grid-security/certificates/
     - $ESGF_CONFIG/cog/cog_config/:/usr/local/cog/cog_config/
     - $ESGF_CONFIG/esg/config/:/esg/config/
     - $PWD/httpd/esgf-docker-entrypoint.sh:/esgf-docker-entrypoint.sh
   environment:
     - SSL_CERT_DIR=/etc/grid-security/certificates
     - COG_CONFIG_DIR=/usr/local/cog/cog_config
   volumes_from:
     - esgf_cog_app
   ports:
     - "80:80"
     - "443:443"
   image: esgfhub/esgf-httpd
   container_name: esgf_httpd
   entrypoint: /esgf-docker-entrypoint.sh
   # httpd URLs must use hostname='my.esgf.node'
   networks:
     default: {}
     mynet:
       aliases:
         - my.esgf.node

