# required env variables:
# SOLR_DATA_DIR : points to Solr index directory
# 	example: export SOLR_DATA_DIR=/Users/cinquini/data/solr-index
# DOCKER_IP: IP address of Docker host
#       example: export DOCKER_IP=`docker-machine ip`

esgf_solr_app:
  expose:
    - "8983"
    - "8984"
  ports:
    - "8983:8983"
    - "8984:8984" 
  image: esgfhub/esgf-solr
  container_name: esgf_solr
  volumes:
   - $SOLR_DATA_DIR:/esg/solr-index

esgf_search_app:
  image: esgfhub/esgf-search
  expose:
    - "8080"
    - "8443"
  ports:
    - "8080:8080"
    - "8443:8443"
  links:
    - esgf_solr_app
  container_name: esgf_search

esgf_postgres_app:
   image: esgfhub/esgf-postgres
   expose:
     - "5432"
   ports:
     - "5432:5432"
   container_name: esgf_postgres

esgf_cog_app:
   image: esgfhub/esgf-cog
   expose:
     - "8000"
   ports:
     - "8000:8000"
   links:
     - esgf_postgres_app
     - esgf_search_app
   volumes:
      - $PWD/cog/esgf-cog_settings.cfg:/usr/local/cog/cog_config/esgf-cog_settings.cfg
   command: $DOCKER_IP true false
   container_name: esgf_cog

esgf_httpd_app:
   volumes:
     - $PWD/httpd/esgf-httpd.conf:/etc/httpd/conf.d/esgf-httpd.conf
     - $PWD/httpd/esgf-docker-entrypoint.sh:/esgf-docker-entrypoint.sh
   volumes_from:
     - esgf_cog_app
   ports:
     - "80:80"
   image: esgfhub/esgf-httpd
   links:
     - esgf_search_app
     - esgf_cog_app
     - esgf_postgres_app
   container_name: esgf_httpd
   entrypoint: /esgf-docker-entrypoint.sh
