# docker-compose configuration for ESGF data node
#
# required env variables:
#
# ESGF_CONFIG : points to the root ESGF configuration directory
#       example: export ESGF_CONFIG=/Users/cinquini/ESGF_CONFIG
# SOLR_DATA_DIR : points to Solr index directory
# 	example: export SOLR_DATA_DIR=/Users/cinquini/ESGF_CONFIG/solr-index
# TDS_CONTENT_ROOT : point to root directory above TDS catalogs thredds/
#       example: export TDS_CONTENT_ROOT=/esg/content
# ESGF_HOSTNAME: HostName or IP address for apache httpd front-end server
#       example: export ESGF_HOSTNAME=my.esgf.node
#       example: export ESGF_HOSTNAME=`docker-machine ip`

version: '2'

networks:
  mynet:
    external:
      name: esgf-network

services:

  esgf-data-node:
    image: esgfhub/esgf-data-node
    container_name: data-node
    expose:
      - "8080"
      - "8443"
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      default: {}
      mynet: {}
    volumes:
      - $ESGF_CONFIG/esg/config/:/esg/config/
    #  - $TDS_CONTENT_ROOT:/esg/content
      - $ESGF_CONFIG/webapps/thredds/WEB-INF/web.xml:/usr/local/tomcat/webapps/thredds/WEB-INF/web.xml
    environment:
     - ESGF_HOSTNAME
    depends_on:
      - esgf-postgres

  esgf-postgres:
     image: esgfhub/esgf-postgres
     expose:
       - "5432"
     ports:
       - "5432:5432"
     container_name: postgres

  esgf-httpd:
   image: esgfhub/esgf-httpd
   container_name: httpd
   entrypoint: /usr/local/bin/docker-entrypoint.sh
   volumes:
     # mapped volumes (mounted inside Docker Host, persisted even after docker-compose down)
     - $ESGF_CONFIG/httpd/certs/:/etc/certs/
     # FIXME: customize httpd configuration
     - $ESGF_CONFIG/httpd/conf/esgf-httpd.conf:/etc/httpd/conf.d/esgf-httpd.conf
     - $ESGF_CONFIG/grid-security/certificates/:/etc/grid-security/certificates/
     - $ESGF_CONFIG/cog/cog_config/:/usr/local/cog/cog_config/
     - $ESGF_CONFIG/esg/config/:/esg/config/
   ports:
     - "80:80"
     - "443:443"
   # httpd URLs must use hostname=$ESGF_HOSTNAME
   networks:
     default: {}
     mynet:
       aliases:
         - "${ESGF_HOSTNAME}"
