# required env variables:
#
# ESGF_CONFIG : points to the root ESGF configuration directory
#       example: export ESGF_CONFIG=/Users/cinquini/ESGF_CONFIG
# SOLR_DATA_DIR : points to Solr index directory
# 	example: export SOLR_DATA_DIR=/Users/cinquini/ESGF_CONFIG/solr-index
# TDS_CONTENT_ROOT : point to root directory above TDS catalogs thredds/
#       example: export TDS_CONTENT_ROOT=/esg/content
# ESGF_HOSTNAME: HostName or IP address for apache httpd front-end server
#       example: export ESGF_HOSTNAME=my.esgf.node
#       example: export ESGF_HOSTNAME=`docker-machine ip`

version: '2'

networks:
  mynet:
    external:
      name: esgf-network

services:

  esgf_data_node_app:
    expose:
      - "8080"
      - "8443"
    ports:
      - "8080:8080"
      - "8443:8443"
    image: esgfhub/esgf-data-node
    container_name: esgf-data-node
    networks:
      default: {}
      mynet: {}
    volumes:
      - $ESGF_CONFIG/esg/config/:/esg/config/
    #  - $TDS_CONTENT_ROOT:/esg/content
      - $ESGF_CONFIG/webapps/thredds/WEB-INF/web.xml:/usr/local/tomcat/webapps/thredds/WEB-INF/web.xml
    environment:
     - ESGF_HOSTNAME
    depends_on:
      - esgf-postgres

  esgf-idp-node:
    image: esgfhub/esgf-idp-node
    expose:
      - "8080"
      - "8443"
    ports:
      - "8082:8080"
      - "8445:8443"
    container_name: idp-node
    networks:
      default: {}
      mynet: {}
    volumes:
      - $ESGF_CONFIG/esg/config/:/esg/config/
    depends_on:
      - esgf-postgres
    #environment:
    # - ESGF_HOME=/esg

  esgf-solr:
    expose:
      - "8983"
      - "8984"
    ports:
      - "8983:8983"
      - "8984:8984" 
    image: esgfhub/esgf-solr
    container_name: solr
    volumes:
     - $SOLR_DATA_DIR:/esg/solr-index
    networks:
      default: {}
      mynet: {}

  esgf-index-node:
    image: esgfhub/esgf-index-node
    expose:
      - "8080"
      - "8443"
    ports:
      - "8081:8080"
      - "8444:8443"
    depends_on:
      - esgf-solr
    volumes:
      - $ESGF_CONFIG/esg/config/:/esg/config/
    container_name: index-node
    networks:
      default: {}
      mynet: {}

  esgf-postgres:
     image: esgfhub/esgf-postgres
     expose:
       - "5432"
     ports:
       - "5432:5432"
     container_name: postgres

  esgf-cog:
     image: esgfhub/esgf-cog
     expose:
       - "8000"
     ports:
       - "8000:8000"
     volumes:
       - $ESGF_CONFIG/cog/cog_config/:/usr/local/cog/cog_config/
       - $ESGF_CONFIG/esg/config/:/esg/config/
       - cog_install_dir:/usr/local/cog/cog_install
       - cog_venv_dir:/usr/local/cog/venv
     #command: $ESGF_HOSTNAME true true # keep django runnining on port 8000
     command: $ESGF_HOSTNAME true false
     container_name: cog
     depends_on:
       - esgf-postgres

  esgf-httpd:
   volumes:
     # mapped volumes (mounted inside Docker Host, persisted even after docker-compose down)
     - $ESGF_CONFIG/httpd/certs/:/etc/certs/
     - $ESGF_CONFIG/httpd/conf/esgf-httpd.conf:/etc/httpd/conf.d/esgf-httpd.conf
     - $ESGF_CONFIG/grid-security/certificates/:/etc/grid-security/certificates/
     - $ESGF_CONFIG/cog/cog_config/:/usr/local/cog/cog_config/
     - $ESGF_CONFIG/esg/config/:/esg/config/
     # named volumes (mounted inside Docker Engine, removed with docker-compose down)
     - cog_install_dir:/usr/local/cog/cog_install
     - cog_venv_dir:/usr/local/cog/venv
   environment:
     - SSL_CERT_DIR=/etc/grid-security/certificates
     - COG_CONFIG_DIR=/usr/local/cog/cog_config
   #volumes_from:
   #  - esgf-cog
   ports:
     - "80:80"
     - "443:443"
   image: esgfhub/esgf-httpd
   container_name: httpd
   entrypoint: /usr/local/bin/docker-entrypoint.sh
   depends_on:
     - esgf-cog
   # httpd URLs must use hostname=$ESGF_HOSTNAME
   networks:
     default: {}
     mynet:
       aliases:
         - "${ESGF_HOSTNAME}"

volumes:
  cog_install_dir:
  cog_venv_dir:
