esgf_solr_app:
  expose:
    - "8983"
    - "8984"
  ports:
    - "8983:8983"
    - "8984:8984" 
  image: esgfhub/esgf-solr
  container_name: esgf_solr
esgf_search_app:
  image: esgfhub/esgf-search
  expose:
    - "8080"
    - "8443"
  ports:
    - "8080:8080"
    - "8443:8443"
  links:
    - esgf_solr_app
  container_name: esgf_search
esgf_httpd_app:
   volumes:
    - $PWD/localhost.conf:/etc/httpd/conf.d/localhost.conf
   ports:
     - "80:80"
   image: esgfhub/esgf-httpd
   links:
     - esgf_search_app:esgf_search_app
   container_name: esgf_httpd
